-- AUTO-GENERATED BY hs-bundler. DO NOT EDIT DIRECTLY.
-- Edit source modules under src/ instead.

local __modules = {}
local __cached = {}

local function __require(modname)
  if __cached[modname] then return __cached[modname] end
  if __modules[modname] then
    local res = __modules[modname]()
    __cached[modname] = (res == nil and true or res)
    return __cached[modname]
  end
  return require(modname)
end

__modules["hud"] = function()
local hsWebview = require("hs.webview")
local hsUsercontent = require("hs.webview.usercontent")

local config = __require("config")
local midi = __require("midi")
local transposer = __require("transposer")
local arpeggiator = __require("arpeggiator")

local state = config.state
local SCALES = config.SCALES
local NOTE_NAMES = config.NOTE_NAMES
local numberRowControls = config.numberRowControls
local upperRowKeys = config.upperRowKeys
local lowerRowKeys = config.lowerRowKeys
local homeRowControls = config.homeRowControls
local ARP_DIRECTIONS = state.ARP_DIRECTIONS
local ARP_RATES = state.ARP_RATES
local ARP_GATES = state.ARP_GATES

local HTML_UI_CONTENT = __require("ui_html")

_G.activeWatchers = _G.activeWatchers or {}

local controlsModule = nil

local function setControlsModule(m)
  controlsModule = m
end

local function updateWebviewHud(spotlightInfo, activeArpPitch)
  if not _G.activeWatchers.midiWebview then return end

  local baseW, baseH = 810, 330
  local effectiveScale = state.zoomLevel * state.BASE_HUD_SCALE
  local newW = math.floor(baseW * effectiveScale)
  local newH = math.floor(baseH * effectiveScale)
  local curFrame = _G.activeWatchers.midiWebview:frame()

  if curFrame.w ~= newW or curFrame.h ~= newH then
    local screen = hs.screen.mainScreen():frame()
    local cx = curFrame.x + (curFrame.w / 2)
    local cy = curFrame.y + (curFrame.h / 2)
    local nx = math.floor(cx - (newW / 2))
    local ny = math.floor(cy - (newH / 2))
    nx = math.max(screen.x, math.min(screen.x + screen.w - newW, nx))
    ny = math.max(screen.y, math.min(screen.y + screen.h - newH, ny))
    _G.activeWatchers.midiWebview:frame({ x = nx, y = ny, w = newW, h = newH })
    _G.activeWatchers.hudX = nx
    _G.activeWatchers.hudY = ny
    hs.settings.set("qwertyMidi_hudX", nx)
    hs.settings.set("qwertyMidi_hudY", ny)
  end

  hs.settings.set("qwertyMidi_zoomLevel", state.zoomLevel)
  
  local modeFrac = (state.currentScaleIdx - 0.5) / #SCALES
  local modeName = SCALES[state.currentScaleIdx].name
  
  local octStr = (state.octaveShift >= 0 and "+" or "") .. (state.octaveShift / 12) .. " Oct"
  local trnspStr = (state.transposeShift ~= 0) and ("Trnsp: " .. (state.transposeShift >= 0 and "+" or "") .. state.transposeShift .. "st") or ""
  local susStr = state.sustainActive and "SUS: ON" or ""
  local shiftStr = state.shiftHeld and "[SHIFT]" or ""

  local statusParts = {}
  if trnspStr ~= "" then table.insert(statusParts, trnspStr) end
  if susStr ~= "" then table.insert(statusParts, susStr) end
  if shiftStr ~= "" then table.insert(statusParts, shiftStr) end
  local statusStr = table.concat(statusParts, "  •  ")

  local topOctaveStr = (state.topRowOctaveOffset >= 0 and "+" or "") .. math.floor(state.topRowOctaveOffset / 12)
  local bottomOctaveStr = (state.octaveShift >= 0 and "+" or "") .. math.floor(state.octaveShift / 12)

  local keyUpdates = {}

  for code, cData in pairs(numberRowControls) do
    local isMode = (cData.action == "modeDown" or cData.action == "modeUp")
    keyUpdates[tostring(code)] = {
      note = cData.name,
      isControl = true,
      typeClass = isMode and "mode-control" or "",
      pressed = (state.pressedKeys[code] ~= nil)
    }
  end

  for code, kData in pairs(upperRowKeys) do
    local noteNum = transposer.getTransposedPitch(kData.baseNote, true)
    local intervalIdx = transposer.getIntervalInfo(noteNum)
    local noteName = transposer.noteNumToName(noteNum)
    local typeClass = ""

    if intervalIdx == 1 then
      typeClass = "root-key"
    elseif intervalIdx == 3 then
      typeClass = "third-key"
    elseif intervalIdx == 5 then
      typeClass = "fifth-key"
    end

    local isPressed = (state.pressedKeys[code] ~= nil)
    if state.arpEnabled and activeArpPitch and noteNum == activeArpPitch then
      isPressed = true
    end

    keyUpdates[tostring(code)] = {
      note = noteName,
      typeClass = typeClass,
      pressed = isPressed
    }
  end

  for code, kData in pairs(lowerRowKeys) do
    local noteNum = transposer.getTransposedPitch(kData.baseNote, false)
    local intervalIdx = transposer.getIntervalInfo(noteNum)
    local noteName = transposer.noteNumToName(noteNum)
    local typeClass = ""

    if intervalIdx == 1 then
      typeClass = "root-key"
    elseif intervalIdx == 3 then
      typeClass = "third-key"
    elseif intervalIdx == 5 then
      typeClass = "fifth-key"
    end

    local isPressed = (state.pressedKeys[code] ~= nil)
    if state.arpEnabled and activeArpPitch and noteNum == activeArpPitch then
      isPressed = true
    end

    keyUpdates[tostring(code)] = {
      note = noteName,
      typeClass = typeClass,
      pressed = isPressed
    }
  end

  for code, cData in pairs(homeRowControls) do
    local label = state.shiftHeld and cData.shiftName or cData.name
    local act = state.shiftHeld and cData.shiftAction or cData.action
    local isSustain = (code == 0 or code == 48)
    local isMode = (act == "modeDown" or act == "modeUp")
    keyUpdates[tostring(code)] = {
      note = label,
      isControl = true,
      typeClass = isMode and "mode-control" or "",
      pressed = (state.pressedKeys[code] ~= nil),
      sustainActive = isSustain and state.sustainActive
    }
  end

  local modVal = state.ccStates[1] or 0

  local bpmDisplayStr
  if state.bpmInputMode then
    bpmDisplayStr = state.bpmInputBuffer .. "\226\150\140"
  else
    bpmDisplayStr = arpeggiator.formatBpm(state.arpBpm) .. " BPM"
  end

  local payload = {
    rootIdx = state.currentRoot,
    modeName = modeName,
    arpEnabled = state.arpEnabled,
    arpDirectionIdx = state.arpDirectionIdx,
    arpRateIdx = state.arpRateIdx,
    arpGateIdx = state.arpGateIdx,
    bpmDisplay = bpmDisplayStr,
    bpmEditing = state.bpmInputMode,
    arpTopEnabled = state.arpTopEnabled,
    arpBottomEnabled = state.arpBottomEnabled,
    statusText = statusStr,
    topOctaveStr = topOctaveStr,
    bottomOctaveStr = bottomOctaveStr,
    topVolPercent = math.floor((state.topRowVolume / 127) * 100),
    bottomVolPercent = math.floor((state.bottomRowVolume / 127) * 100),
    effectiveTopVolPercent = math.floor((transposer.getEffectiveRowVelocity(true) / 127) * 100),
    modeFrac = modeFrac,
    modWheel = modVal,
    zoomLevel = effectiveScale,
    spotlight = spotlightInfo,
    keys = keyUpdates
  }

  local jsonStr = hs.json.encode(payload)
  _G.activeWatchers.midiWebview:evaluateJavaScript("renderHud(" .. jsonStr .. ")")
end

local function createMidiWebview()
  if _G.activeWatchers.midiWebview then
    _G.activeWatchers.midiWebview:delete()
    _G.activeWatchers.midiWebview = nil
  end

  local screen = hs.screen.mainScreen():frame()
  local effectiveScale = state.zoomLevel * state.BASE_HUD_SCALE
  local width = math.floor(810 * effectiveScale)
  local height = math.floor(330 * effectiveScale)
  local savedX = hs.settings.get("qwertyMidi_hudX")
  local savedY = hs.settings.get("qwertyMidi_hudY")
  local hudX = savedX or _G.activeWatchers.hudX or math.floor(screen.x + (screen.w - width) / 2)
  local hudY = savedY or _G.activeWatchers.hudY or math.floor(screen.y + screen.h - height - 60)

  local uc = hsUsercontent.new("midiControllerUC")
  uc:setCallback(function(msg)
    if not msg or not msg.body then return end
    local body = msg.body
    if body.type == "domReady" then
      updateWebviewHud()
    elseif body.type == "keyDown" and body.code then
      if controlsModule then controlsModule.handleKeyDown(body.code) end
    elseif body.type == "keyUp" and body.code then
      if controlsModule then controlsModule.handleKeyUp(body.code) end
    elseif body.type == "setRoot" and body.root ~= nil then
      state.currentRoot = math.max(0, math.min(11, body.root))
      arpeggiator.updateLatchedArpNotes()
      local rootName = NOTE_NAMES[state.currentRoot + 1]
      local spot = {
        title = "ROOT NOTE",
        value = rootName,
        subtext = rootName .. " " .. SCALES[state.currentScaleIdx].name,
        targetId = "root-select",
        color = "#d4a359"
      }
      updateWebviewHud(spot)
    elseif body.type == "setModeIdx" and body.modeIdx ~= nil then
      state.currentScaleIdx = math.max(1, math.min(#SCALES, body.modeIdx))
      arpeggiator.updateLatchedArpNotes()
      local scaleInfo = SCALES[state.currentScaleIdx]
      local spot = {
        title = "SCALE / MODE",
        value = scaleInfo.name,
        subtext = scaleInfo.brightTag,
        targetId = "mode-thumb",
        color = "#d4a359"
      }
      updateWebviewHud(spot)
    elseif body.type == "toggleArpPower" then
      arpeggiator.toggleArpPower()
    elseif body.type == "setArpDirection" and body.directionIdx ~= nil then
      state.arpDirectionIdx = math.max(1, math.min(#ARP_DIRECTIONS, body.directionIdx))
      local spot = {
        title = "ARP DIRECTION",
        value = ARP_DIRECTIONS[state.arpDirectionIdx],
        subtext = state.arpEnabled and "Active Pattern" or "Arp Disabled",
        targetId = "arp-dir-select",
        color = "#d4a359"
      }
      updateWebviewHud(spot)
    elseif body.type == "setArpRate" and body.rateIdx ~= nil then
      state.arpRateIdx = math.max(1, math.min(#ARP_RATES, body.rateIdx))
      arpeggiator.applyBpmChange()
      local spot = {
        title = "ARP RATE",
        value = ARP_RATES[state.arpRateIdx].label,
        subtext = "Note Division",
        targetId = "arp-rate-select",
        color = "#d4a359"
      }
      updateWebviewHud(spot)
    elseif body.type == "setArpGate" and body.gateIdx ~= nil then
      state.arpGateIdx = math.max(1, math.min(#ARP_GATES, body.gateIdx))
      local spot = {
        title = "ARP NOTE LENGTH",
        value = ARP_GATES[state.arpGateIdx].label,
        subtext = "Gate Duration",
        targetId = "arp-gate-select",
        color = "#d4a359"
      }
      updateWebviewHud(spot)
    elseif body.type == "enterBpmEdit" then
      state.bpmInputMode = true
      state.bpmBeforeEdit = state.arpBpm
      state.bpmInputBuffer = ""
      updateWebviewHud()
    elseif body.type == "bpmUp" then
      state.arpBpm = math.min(300, state.arpBpm + 1)
      arpeggiator.applyBpmChange()
      updateWebviewHud()
    elseif body.type == "bpmDown" then
      state.arpBpm = math.max(20, state.arpBpm - 1)
      arpeggiator.applyBpmChange()
      updateWebviewHud()
    elseif body.type == "dragBpm" and body.delta ~= nil then
      state.arpBpm = math.max(20.0, math.min(300.0, state.arpBpm + body.delta))
      arpeggiator.applyBpmChange()
      updateWebviewHud()
    elseif body.type == "toggleArpTop" then
      if state.arpTopEnabled or not state.arpBottomEnabled then
        state.arpTopEnabled = not state.arpTopEnabled
      end
      updateWebviewHud()
    elseif body.type == "toggleArpBottom" then
      if state.arpBottomEnabled or not state.arpTopEnabled then
        state.arpBottomEnabled = not state.arpTopEnabled
      end
      updateWebviewHud()
    elseif body.type == "dragOctave" and body.row and body.direction then
      if body.row == "top" then
        state.topRowOctaveOffset = math.max(-36, math.min(36, state.topRowOctaveOffset + (body.direction * 12)))
      else
        state.octaveShift = math.max(-36, math.min(36, state.octaveShift + (body.direction * 12)))
      end
      updateWebviewHud()
    elseif body.type == "dragWindow" and body.dx and body.dy then
      if _G.activeWatchers.midiWebview then
        local frame = _G.activeWatchers.midiWebview:frame()
        local newX = math.floor(frame.x + body.dx)
        local newY = math.floor(frame.y + body.dy)
        _G.activeWatchers.midiWebview:frame({ x = newX, y = newY, w = frame.w, h = frame.h })
        _G.activeWatchers.hudX = newX
        _G.activeWatchers.hudY = newY
        hs.settings.set("qwertyMidi_hudX", newX)
        hs.settings.set("qwertyMidi_hudY", newY)
      end
    end
  end)

  local rect = { x = hudX, y = hudY, w = width, h = height }
  local wv = hsWebview.new(rect, { developerExtrasEnabled = false }, uc)
  wv:windowTitle("MIDI Controller HUD")
  wv:windowStyle({ "borderless", "utility" })
  wv:transparent(true)
  wv:html(HTML_UI_CONTENT)
  wv:level(hs.canvas.windowLevels.floating)
  wv:behavior(hs.canvas.windowBehaviors.canJoinAllSpaces)
  wv:show()

  wv:windowCallback(function(action, webview)
    if action == "closing" then
      _G.activeWatchers.midiWebview = nil
    end
  end)

  _G.activeWatchers.midiWebview = wv

  hs.timer.doAfter(0.05, function()
    if _G.activeWatchers.midiWebview then
      updateWebviewHud()
    end
  end)
  hs.timer.doAfter(0.25, function()
    if _G.activeWatchers.midiWebview then
      updateWebviewHud()
    end
  end)

  return wv
end

return {
  setControlsModule = setControlsModule,
  updateWebviewHud = updateWebviewHud,
  createMidiWebview = createMidiWebview
}

end

__modules["init"] = function()
local config = __require("config")
local midi = __require("midi")
local transposer = __require("transposer")
local arpeggiator = __require("arpeggiator")
local hud = __require("hud")
local controls = __require("controls")

local state = config.state

_G.activeWatchers = _G.activeWatchers or {}

arpeggiator.setHudModule(hud)
hud.setControlsModule(controls)

function _G.toggleMidiMode(newState)
  if newState == nil then
    state.midiActive = not state.midiActive
  else
    state.midiActive = newState
  end

  if state.midiActive then
    _G.activeWatchers.midiKeyTap:start()
    _G.activeWatchers.midiScrollTap:start()
    local h = hud.createMidiWebview()
    h:show()
  else
    _G.activeWatchers.midiKeyTap:stop()
    _G.activeWatchers.midiScrollTap:stop()
    state.pressedKeys = {}
    arpeggiator.stopArpTimer()
    state.arpHeldNotes = {}
    state.arpKeysCurrentlyHeld = {}
    if _G.activeWatchers.midiWebview then
      _G.activeWatchers.midiWebview:hide()
    end
  end
  hs.alert.show("🎹 MIDI Mode: " .. (state.midiActive and "ON" or "OFF"))
end

_G.activeWatchers.midiScrollTap = hs.eventtap.new({ hs.eventtap.event.types.scrollWheel }, function(event)
  if not state.midiActive then return false end

  local deltaY = event:getProperty(hs.eventtap.event.properties.scrollWheelEventDeltaAxis1) or 0
  if deltaY == 0 then
    deltaY = event:getProperty(hs.eventtap.event.properties.scrollWheelEventPointDeltaAxis1) or 0
  end

  if deltaY ~= 0 then
    if state.shiftHeld then
      local avgVol = (state.topRowVolume + state.bottomRowVolume) / 2
      _G.activeWatchers.volAccumulator = _G.activeWatchers.volAccumulator or avgVol
      local sensitivity = 0.25
      _G.activeWatchers.volAccumulator = math.max(0, math.min(127, _G.activeWatchers.volAccumulator - (deltaY * sensitivity)))
      local newVol = math.floor(_G.activeWatchers.volAccumulator + 0.5)

      local deltaVol = newVol - math.floor(avgVol + 0.5)
      if deltaVol ~= 0 then
        state.topRowVolume = math.max(0, math.min(127, state.topRowVolume + deltaVol))
        state.bottomRowVolume = math.max(0, math.min(127, state.bottomRowVolume + deltaVol))
        local spot = {
          title = "ROW VOLUMES",
          value = "TOP " .. math.floor((state.topRowVolume / 127) * 100) .. "% | BOT " .. math.floor((state.bottomRowVolume / 127) * 100) .. "%",
          subtext = "Dual Row Volume Level",
          targetId = "header",
          color = "#d4a359"
        }
        hud.updateWebviewHud(spot)
      end
    else
      local currentMod = state.ccStates[1] or 0
      _G.activeWatchers.modAccumulator = _G.activeWatchers.modAccumulator or currentMod
      local sensitivity = 0.15
      _G.activeWatchers.modAccumulator = math.max(0, math.min(127, _G.activeWatchers.modAccumulator - (deltaY * sensitivity)))
      local newMod = math.floor(_G.activeWatchers.modAccumulator + 0.5)

      if newMod ~= state.ccStates[1] then
        state.ccStates[1] = newMod
        midi.sendMidiCC(1, newMod)
        local spot = {
          title = "MOD WHEEL (CC #1)",
          value = tostring(newMod),
          subtext = math.floor((newMod / 127) * 100) .. "% Intensity",
          targetId = "header",
          color = "#d4a359"
        }
        hud.updateWebviewHud(spot)
      end
    end
    return true
  end

  return false
end)

_G.activeWatchers.midiKeyTap = hs.eventtap.new({ hs.eventtap.event.types.keyDown, hs.eventtap.event.types.keyUp, hs.eventtap.event.types.flagsChanged }, function(event)
  if not state.midiActive then return false end

  local flags = event:getFlags()

  if state.bpmInputMode then
    if event:getType() == hs.eventtap.event.types.flagsChanged then
      return false
    end
    if flags.cmd or flags.ctrl then return false end
    local code = event:getProperty(hs.eventtap.event.properties.keyboardEventKeycode)
    local isDown = (event:getType() == hs.eventtap.event.types.keyDown)
    if isDown then
      return arpeggiator.handleBpmInput(code, flags)
    end
    return true
  end

  if flags.cmd or flags.alt or flags.ctrl then
    return false
  end

  local isShiftNow = flags.shift
  if isShiftNow ~= state.shiftHeld then
    state.shiftHeld = isShiftNow
    hud.updateWebviewHud()
  end

  if event:getType() == hs.eventtap.event.types.flagsChanged then
    return false
  end

  local code = event:getProperty(hs.eventtap.event.properties.keyboardEventKeycode)
  local isDown = (event:getType() == hs.eventtap.event.types.keyDown)

  if isDown then
    return controls.handleKeyDown(code)
  else
    return controls.handleKeyUp(code)
  end
end)

_G.activeWatchers.midiToggleHotkey = hs.hotkey.bind({ "cmd", "alt" }, "M", function()
  _G.toggleMidiMode()
end)

return {
  toggleMidiMode = _G.toggleMidiMode
}

end

__modules["arpeggiator"] = function()
local config = __require("config")
local midi = __require("midi")
local transposer = __require("transposer")

local state = config.state
local upperRowKeys = config.upperRowKeys
local lowerRowKeys = config.lowerRowKeys
local ARP_DIRECTIONS = state.ARP_DIRECTIONS
local ARP_RATES = state.ARP_RATES
local ARP_GATES = state.ARP_GATES
local DIGIT_KEYCODES = state.DIGIT_KEYCODES

local hudModule = nil

local function setHudModule(m)
  hudModule = m
end

local function updateHud(spotlightInfo, activeArpPitch)
  if hudModule and hudModule.updateWebviewHud then
    hudModule.updateWebviewHud(spotlightInfo, activeArpPitch)
  end
end

local function stopArpTimer()
  if state.arpGateTimer then
    state.arpGateTimer:stop()
    state.arpGateTimer = nil
  end
  if state.arpTimer then
    state.arpTimer:stop()
    state.arpTimer = nil
  end
  if state.arpCurrentPitch then
    midi.sendMidiNote("noteOff", state.arpCurrentPitch, 0)
    state.arpCurrentPitch = nil
  end
  state.arpStepIndex = 1
  state.arpStepDirection = 1
end

local function getArpIntervalSeconds()
  local rateFactor = ARP_RATES[state.arpRateIdx] and ARP_RATES[state.arpRateIdx].factor or 0.5
  return (60.0 / state.arpBpm) * rateFactor
end

local function arpTick()
  local pitchList = {}
  for code, pitch in pairs(state.arpHeldNotes) do
    table.insert(pitchList, pitch)
  end
  table.sort(pitchList)

  if #pitchList == 0 then
    if state.arpGateTimer then
      state.arpGateTimer:stop()
      state.arpGateTimer = nil
    end
    if state.arpCurrentPitch then
      midi.sendMidiNote("noteOff", state.arpCurrentPitch, 0)
      state.arpCurrentPitch = nil
      updateHud()
    end
    return
  end

  if state.arpDirectionIdx == 1 then -- UP
    state.arpStepIndex = ((state.arpStepIndex - 1) % #pitchList) + 1
  elseif state.arpDirectionIdx == 2 then -- DOWN
    state.arpStepIndex = ((state.arpStepIndex - 2 + #pitchList) % #pitchList) + 1
  elseif state.arpDirectionIdx == 3 then -- UP-DOWN
    if state.arpStepIndex > #pitchList then
      state.arpStepIndex = math.max(1, #pitchList - 1)
      state.arpStepDirection = -1
    elseif state.arpStepIndex < 1 then
      state.arpStepIndex = math.min(#pitchList, 2)
      state.arpStepDirection = 1
    end
  elseif state.arpDirectionIdx == 4 then -- RANDOM
    state.arpStepIndex = math.random(1, #pitchList)
  end

  local nextPitch = pitchList[state.arpStepIndex]

  if state.arpDirectionIdx == 3 then
    if #pitchList == 1 then
      state.arpStepIndex = 1
      state.arpStepDirection = 1
    else
      state.arpStepIndex = state.arpStepIndex + state.arpStepDirection
      if state.arpStepIndex > #pitchList then
        state.arpStepIndex = math.max(1, #pitchList - 1)
        state.arpStepDirection = -1
      elseif state.arpStepIndex < 1 then
        state.arpStepIndex = math.min(#pitchList, 2)
        state.arpStepDirection = 1
      end
    end
  elseif state.arpDirectionIdx == 1 then
    state.arpStepIndex = state.arpStepIndex + 1
  elseif state.arpDirectionIdx == 2 then
    state.arpStepIndex = state.arpStepIndex - 1
  end

  if state.arpGateTimer then
    state.arpGateTimer:stop()
    state.arpGateTimer = nil
  end

  if state.arpCurrentPitch then
    midi.sendMidiNote("noteOff", state.arpCurrentPitch, 0)
  end

  local isTopRowArpNote = false
  for code, p in pairs(state.arpHeldNotes) do
    if p == nextPitch and upperRowKeys[code] then
      isTopRowArpNote = true
      break
    end
  end
  local vel = transposer.getEffectiveRowVelocity(isTopRowArpNote)
  midi.sendMidiNote("noteOn", nextPitch, vel)
  state.arpCurrentPitch = nextPitch

  updateHud(nil, nextPitch)

  local gateRatio = ARP_GATES[state.arpGateIdx] and ARP_GATES[state.arpGateIdx].ratio or 0.80
  if gateRatio < 1.00 then
    local gateDuration = getArpIntervalSeconds() * gateRatio
    state.arpGateTimer = hs.timer.doAfter(gateDuration, function()
      if state.arpCurrentPitch == nextPitch then
        midi.sendMidiNote("noteOff", state.arpCurrentPitch, 0)
        state.arpCurrentPitch = nil
        updateHud()
      end
      state.arpGateTimer = nil
    end)
  end
end

local function startArpTimer(preserveState)
  if state.arpTimer then return end
  local intervalSeconds = getArpIntervalSeconds()
  if not preserveState then
    state.arpStepIndex = 1
    state.arpStepDirection = 1
    arpTick()
  end
  state.arpTimer = hs.timer.doEvery(intervalSeconds, arpTick)
end

local function arpAddNote(code, pitch)
  local numPhysicalHeld = 0
  for _ in pairs(state.arpKeysCurrentlyHeld) do numPhysicalHeld = numPhysicalHeld + 1 end

  if state.sustainActive and numPhysicalHeld == 0 then
    state.arpHeldNotes = {}
    if state.arpCurrentPitch then
      midi.sendMidiNote("noteOff", state.arpCurrentPitch, 0)
      state.arpCurrentPitch = nil
    end
  end

  state.arpKeysCurrentlyHeld[code] = true
  state.arpHeldNotes[code] = pitch

  if not state.arpTimer then
    startArpTimer()
  end
end

local function arpRemoveNote(code)
  state.arpKeysCurrentlyHeld[code] = nil

  if state.sustainActive then
    return
  end

  state.arpHeldNotes[code] = nil
  local count = 0
  for _ in pairs(state.arpHeldNotes) do count = count + 1 end
  if count == 0 then
    stopArpTimer()
    updateHud()
  end
end

local function formatBpm(bpm)
  if bpm == math.floor(bpm) then
    return tostring(math.floor(bpm))
  else
    return string.format("%.1f", bpm)
  end
end

local function applyBpmChange()
  if state.arpTimer then
    state.arpTimer:setNextTrigger(getArpIntervalSeconds())
  end
end

local function updateLatchedArpNotes()
  if not state.arpEnabled or next(state.arpHeldNotes) == nil then return end
  for code, _ in pairs(state.arpHeldNotes) do
    if lowerRowKeys[code] then
      state.arpHeldNotes[code] = transposer.getTransposedPitch(lowerRowKeys[code].baseNote, false)
    elseif upperRowKeys[code] then
      state.arpHeldNotes[code] = transposer.getTransposedPitch(upperRowKeys[code].baseNote, true)
    end
  end
end

local function getArpRowTargetSubtext()
  if state.arpTopEnabled and state.arpBottomEnabled then
    return "Top & Bottom Rows"
  elseif state.arpTopEnabled then
    return "Top Row Only"
  elseif state.arpBottomEnabled then
    return "Bottom Row Only"
  else
    return "No Rows Active"
  end
end

local function toggleArpPower()
  state.arpEnabled = not state.arpEnabled
  if not state.arpEnabled then
    stopArpTimer()
    state.arpHeldNotes = {}
    state.arpKeysCurrentlyHeld = {}
  end
  local spot = {
    title = "ARPEGGIATOR",
    value = state.arpEnabled and "ARP: ON" or "ARP: OFF",
    subtext = state.arpEnabled and ("ON (" .. getArpRowTargetSubtext() .. ") • " .. formatBpm(state.arpBpm) .. " BPM") or "Arp Disabled",
    targetId = "arp-power-btn",
    color = "#d4a359"
  }
  updateHud(spot)
end

local function toggleArp()
  toggleArpPower()
end

local function handleBpmInput(code, flags)
  if code == 53 then -- Escape
    state.arpBpm = state.bpmBeforeEdit
    state.bpmInputMode = false
    state.bpmInputBuffer = ""
    updateHud()
    return true
  elseif code == 36 then -- Return
    if state.bpmInputBuffer ~= "" then
      local val = tonumber(state.bpmInputBuffer)
      if val and val >= 20 and val <= 300 then
        state.arpBpm = val
      end
    end
    state.bpmInputMode = false
    state.bpmInputBuffer = ""
    applyBpmChange()
    updateHud()
    return true
  elseif code == 126 then -- Arrow Up
    local delta = 1
    if flags.shift then delta = 10
    elseif flags.alt then delta = 0.1 end
    state.arpBpm = math.min(300, state.arpBpm + delta)
    state.bpmInputBuffer = ""
    applyBpmChange()
    updateHud()
    return true
  elseif code == 125 then -- Arrow Down
    local delta = 1
    if flags.shift then delta = 10
    elseif flags.alt then delta = 0.1 end
    state.arpBpm = math.max(20, state.arpBpm - delta)
    state.bpmInputBuffer = ""
    applyBpmChange()
    updateHud()
    return true
  elseif code == 51 then -- Backspace
    if #state.bpmInputBuffer > 0 then
      state.bpmInputBuffer = state.bpmInputBuffer:sub(1, -2)
    end
    updateHud()
    return true
  elseif DIGIT_KEYCODES[code] then
    state.bpmInputBuffer = state.bpmInputBuffer .. DIGIT_KEYCODES[code]
    updateHud()
    return true
  elseif code == 47 then -- Period "."
    if not state.bpmInputBuffer:find("%.") then
      state.bpmInputBuffer = state.bpmInputBuffer .. "."
    end
    updateHud()
    return true
  end

  state.bpmInputMode = false
  state.bpmInputBuffer = ""
  updateHud()
  return false
end

return {
  setHudModule = setHudModule,
  stopArpTimer = stopArpTimer,
  getArpIntervalSeconds = getArpIntervalSeconds,
  startArpTimer = startArpTimer,
  arpAddNote = arpAddNote,
  arpRemoveNote = arpRemoveNote,
  formatBpm = formatBpm,
  applyBpmChange = applyBpmChange,
  updateLatchedArpNotes = updateLatchedArpNotes,
  getArpRowTargetSubtext = getArpRowTargetSubtext,
  toggleArpPower = toggleArpPower,
  toggleArp = toggleArp,
  handleBpmInput = handleBpmInput
}

end

__modules["transposer"] = function()
local config = __require("config")
local state = config.state
local SCALES = config.SCALES
local NOTE_NAMES = config.NOTE_NAMES
local WHITE_KEY_INDEX = config.WHITE_KEY_INDEX

local function getEffectiveRowVelocity(isTopRow)
  local isSplitArp = state.arpEnabled and state.arpBottomEnabled and (not state.arpTopEnabled)
  if isTopRow then
    local baseVol = state.topRowVolume
    if isSplitArp then
      baseVol = baseVol + state.splitArpTopBoost
    end
    return math.max(0, math.min(127, baseVol))
  else
    return math.max(0, math.min(127, state.bottomRowVolume))
  end
end

local function getTransposedPitch(basePitch, isTopRow)
  local effectivePitch = basePitch + (isTopRow and state.topRowOctaveOffset or 0) + state.transposeShift
  local octave = math.floor(effectivePitch / 12) - 1
  local noteInOctave = effectivePitch % 12
  local scaleIndex = WHITE_KEY_INDEX[noteInOctave]

  if scaleIndex and scaleIndex ~= -1 then
    local intervals = SCALES[state.currentScaleIdx].intervals
    local targetInterval = intervals[scaleIndex + 1]
    local newPitch = ((octave + 1) * 12) + state.currentRoot + targetInterval + state.octaveShift
    if newPitch >= 0 and newPitch <= 127 then
      return newPitch
    end
  end
  local fallbackPitch = effectivePitch + state.currentRoot + state.octaveShift
  return math.max(0, math.min(127, fallbackPitch))
end

local function noteNumToName(noteNum)
  local octave = math.floor(noteNum / 12) - 1
  local noteName = NOTE_NAMES[(noteNum % 12) + 1]
  return noteName .. octave
end

local function getIntervalInfo(noteNum)
  local noteInOctave = noteNum % 12
  local semitonesFromRoot = (noteInOctave - state.currentRoot + 12) % 12
  local intervals = SCALES[state.currentScaleIdx].intervals

  for idx, interval in ipairs(intervals) do
    if interval == semitonesFromRoot then
      return idx, semitonesFromRoot
    end
  end
  return nil, semitonesFromRoot
end

return {
  getEffectiveRowVelocity = getEffectiveRowVelocity,
  getTransposedPitch = getTransposedPitch,
  noteNumToName = noteNumToName,
  getIntervalInfo = getIntervalInfo
}

end

__modules["ui_html"] = function()
local HTML_UI_CONTENT = [[
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; user-select: none; -webkit-user-select: none; -webkit-font-smoothing: antialiased; }
  html, body {
    background: transparent;
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'SF Pro Text', system-ui, sans-serif;
    width: 100%;
    height: 100%;
    overflow: hidden;
    display: flex;
    justify-content: center;
    align-items: center;
  }
  
  #hud-container {
    width: 810px;
    height: 330px;
    background: rgba(24, 22, 20, 0.96);
    border: 2px solid rgba(70, 64, 58, 0.7);
    border-radius: 14px;
    overflow: visible;
    box-shadow: 0 10px 30px rgba(0,0,0,0.6), inset 0 0 20px rgba(0, 0, 0, 0.6);
    display: flex;
    flex-direction: column;
    padding: 12px 14px 14px 14px;
    position: relative;
    transform-origin: center center;
    transform: scale(1.4);
    transition: border-color 0.15s ease, box-shadow 0.15s ease;
  }

  /* Top Header Spotlight Notification Card */
  .spotlight-card {
    position: absolute;
    top: -5px;
    left: 50%;
    transform: translate(-50%, -100%) scale(1.0);
    background: rgba(20, 18, 16, 0.98);
    border: 1.5px solid #d4a359;
    border-radius: 8px;
    padding: 5px 18px;
    box-shadow: 0 6px 24px rgba(0, 0, 0, 0.9);
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    gap: 10px;
    z-index: 9999;
    pointer-events: none;
    opacity: 1;
    backdrop-filter: blur(10px);
    -webkit-backdrop-filter: blur(10px);
    white-space: nowrap;
  }

  .spotlight-card.hidden {
    opacity: 0;
    display: none;
  }

  .spotlight-title {
    font-size: 10px;
    font-weight: 700;
    letter-spacing: 1px;
    color: #b5aba0;
    text-transform: uppercase;
    margin-bottom: 0;
  }

  .spotlight-val {
    font-size: 15px;
    font-weight: 700;
    color: #ffffff;
    text-shadow: 0 1px 4px rgba(0,0,0,0.6);
    margin-bottom: 0;
    white-space: nowrap;
  }

  .spotlight-sub {
    font-size: 11px;
    font-weight: 600;
    color: #d4a359;
    white-space: nowrap;
  }
  
  /* Dynamic Mod Wheel Glow */
  #hud-container.mod-active {
    box-shadow: 0 0 calc(8px + var(--mod-intensity) * 18px) rgba(212, 163, 89, calc(0.2 + var(--mod-intensity) * 0.25)),
                inset 0 0 calc(10px + var(--mod-intensity) * 15px) rgba(212, 163, 89, calc(0.08 + var(--mod-intensity) * 0.12));
    border-color: rgba(212, 163, 89, calc(0.4 + var(--mod-intensity) * 0.35));
  }

  .mod-gradient-overlay {
    position: absolute;
    top: 0; left: 0; right: 0; bottom: 0;
    border-radius: 14px;
    overflow: hidden;
    pointer-events: none;
    background: linear-gradient(180deg, rgba(212, 163, 89, calc(var(--mod-intensity) * 0.08)) 0%, rgba(200, 140, 60, 0) 100%);
    opacity: 0;
    transition: opacity 0.15s ease;
  }

  #hud-container.mod-active .mod-gradient-overlay {
    opacity: 1;
  }

  /* Header Bar */
  #header {
    height: 48px;
    background: rgba(36, 32, 28, 0.9);
    border-radius: 8px;
    display: flex;
    align-items: center;
    padding: 0 12px;
    margin-bottom: 12px;
    cursor: move;
    -webkit-app-region: drag;
    gap: 10px;
  }

  .badge {
    background: rgba(212, 163, 89, 0.18);
    border: 1.5px solid #d4a359;
    color: #d4a359;
    font-weight: 700;
    font-size: 14px;
    padding: 3px 6px;
    border-radius: 6px;
    display: flex;
    align-items: center;
    justify-content: center;
    white-space: nowrap;
    width: 52px;
    flex-shrink: 0;
    appearance: none;
    -webkit-appearance: none;
    outline: none;
    text-align: center;
    text-align-last: center;
    font-family: inherit;
    -webkit-app-region: no-drag;
    cursor: pointer;
  }

  .badge-small {
    background: rgba(212, 163, 89, 0.15);
    border: 1.5px solid #d4a359;
    color: #d4a359;
    font-weight: 700;
    font-size: 11px;
    padding: 3px 4px;
    border-radius: 6px;
    display: flex;
    align-items: center;
    justify-content: center;
    white-space: nowrap;
    flex-shrink: 0;
    appearance: none;
    -webkit-appearance: none;
    outline: none;
    text-align: center;
    text-align-last: center;
    font-family: inherit;
    -webkit-app-region: no-drag;
    cursor: pointer;
  }

  .badge-small option {
    background: #181614;
    color: #d4a359;
  }
  
  .badge option {
    background: #181614;
    color: #d4a359;
    font-weight: 600;
  }

  .mode-center-block {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    width: 210px;
    flex-shrink: 0;
    -webkit-app-region: no-drag;
  }

  .mode-slider-track {
    width: 190px;
    height: 10px;
    background: linear-gradient(90deg, #d4a359 0%, #b8860b 40%, #706558 70%, #3a342e 100%);
    border-radius: 5px;
    position: relative;
    cursor: pointer;
  }

  .mode-slider-thumb {
    width: 10px;
    height: 16px;
    background: #f2eae1;
    border: 1px solid #333;
    border-radius: 3px;
    position: absolute;
    top: -3px;
    left: 0%;
    transform: translateX(-50%);
    box-shadow: 0 1px 4px rgba(0,0,0,0.6);
    transition: left 0.08s ease;
    pointer-events: none;
  }

  .mode-name-label {
    font-size: 11px;
    font-weight: 700;
    color: #d4a359;
    letter-spacing: 0.5px;
    margin-top: 3px;
    white-space: nowrap;
    text-shadow: 0 1px 2px rgba(0,0,0,0.6);
  }

  .arp-btn {
    background: rgba(212, 163, 89, 0.15);
    border: 1.5px solid #d4a359;
    color: #d4a359;
    font-weight: 700;
    font-size: 11px;
    padding: 4px 8px;
    border-radius: 6px;
    white-space: nowrap;
    flex-shrink: 0;
    cursor: pointer;
    outline: none;
    font-family: inherit;
    -webkit-app-region: no-drag;
    transition: background 0.15s ease, box-shadow 0.15s ease;
  }
  
  .arp-btn:hover {
    background: rgba(212, 163, 89, 0.3);
  }
  
  .arp-btn.arp-active {
    background: rgba(212, 163, 89, 0.45);
    box-shadow: 0 0 8px rgba(212, 163, 89, 0.6);
  }

  .bpm-editor {
    display: flex;
    align-items: center;
    gap: 2px;
    -webkit-app-region: no-drag;
    flex-shrink: 0;
  }

  .bpm-arrow-btn {
    background: rgba(212, 163, 89, 0.12);
    border: 1px solid rgba(212, 163, 89, 0.4);
    color: #d4a359;
    font-size: 10px;
    padding: 2px 5px;
    border-radius: 4px;
    cursor: pointer;
    outline: none;
    font-family: inherit;
    line-height: 1;
    transition: background 0.15s ease;
    -webkit-app-region: no-drag;
  }

  .bpm-arrow-btn:hover {
    background: rgba(212, 163, 89, 0.3);
  }

  .bpm-display {
    font-size: 11px;
    font-weight: 700;
    color: #d4a359;
    padding: 3px 6px;
    border-radius: 4px;
    cursor: text;
    min-width: 60px;
    text-align: center;
    transition: background 0.15s ease, box-shadow 0.15s ease;
    white-space: nowrap;
  }

  .bpm-display:hover {
    background: rgba(212, 163, 89, 0.1);
  }

  .bpm-display.editing {
    background: rgba(212, 163, 89, 0.2);
    box-shadow: 0 0 6px rgba(212, 163, 89, 0.4);
    outline: 1.5px solid #d4a359;
  }

  .row-controls {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 3px;
    flex-shrink: 0;
  }

  .arp-row-toggle {
    font-size: 8px;
    font-weight: 700;
    color: #706558;
    background: rgba(36, 32, 28, 0.8);
    border: 1px solid rgba(112, 101, 88, 0.4);
    border-radius: 4px;
    padding: 1px 6px;
    cursor: pointer;
    outline: none;
    font-family: inherit;
    letter-spacing: 0.5px;
    transition: all 0.15s ease;
    -webkit-app-region: no-drag;
  }

  .arp-row-toggle.active {
    color: #d4a359;
    border-color: rgba(212, 163, 89, 0.6);
    background: rgba(212, 163, 89, 0.15);
    box-shadow: 0 0 4px rgba(212, 163, 89, 0.2);
  }

  .arp-row-toggle:hover {
    background: rgba(212, 163, 89, 0.25);
  }

  .draggable-octave {
    cursor: ns-resize;
    user-select: none;
    -webkit-user-select: none;
  }

  .status-info {
    font-size: 12px;
    color: #b5aba0;
    font-weight: 600;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    flex: 1;
    min-width: 0;
    text-align: right;
  }

  /* Keyboard Grid */
  .keyboard-grid {
    display: flex;
    flex-direction: column;
    gap: 6px;
    flex: 1;
  }

  .keyboard-row {
    display: flex;
    gap: 5px;
  }

  .row-with-indicator {
    display: flex;
    align-items: center;
    justify-content: space-between;
    width: 100%;
  }

  .octave-row-badge {
    font-size: 10.5px;
    font-weight: 700;
    color: #d4a359;
    background: rgba(36, 32, 28, 0.95);
    border: 1.5px solid rgba(212, 163, 89, 0.4);
    border-radius: 6px;
    padding: 3px 8px;
    letter-spacing: 0.5px;
    white-space: nowrap;
    box-shadow: 0 2px 6px rgba(0, 0, 0, 0.4);
  }

  .keyboard-row.number { margin-left: 0px; }
  .keyboard-row.upper { margin-left: 12px; }
  .keyboard-row.home { margin-left: 32px; }
  .keyboard-row.lower { margin-left: 56px; }

  .key-pad {
    width: 58px;
    height: 44px;
    background: rgba(26, 23, 20, 0.98);
    border: 1.5px solid rgba(65, 58, 50, 1.0);
    border-radius: 8px;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    transition: background 0.05s ease, border-color 0.05s ease;
    cursor: pointer;
    flex-shrink: 0;
    -webkit-app-region: no-drag;
  }

  .key-pad:active, .key-pad.pressed {
    background: rgba(55, 48, 40, 1.0);
    border-color: rgba(100, 88, 75, 1.0);
    box-shadow: inset 0 2px 4px rgba(0,0,0,0.5);
  }

  .key-pad .key-code {
    font-size: 12px;
    font-weight: 700;
    color: #f2eae1;
    text-shadow: 0 1px 2px rgba(0, 0, 0, 0.8);
    pointer-events: none;
  }

  .key-pad .key-note {
    font-size: 9.5px;
    font-weight: 500;
    color: rgba(200, 190, 175, 0.95);
    margin-top: 1px;
    white-space: nowrap;
    text-shadow: 0 1px 2px rgba(0, 0, 0, 0.8);
    pointer-events: none;
  }

  /* Glowing Outlines for Note Intervals */
  .key-pad.root-key {
    border-color: rgba(212, 163, 89, 0.9);
    box-shadow: 0 0 10px rgba(212, 163, 89, 0.45), inset 0 0 6px rgba(212, 163, 89, 0.2);
  }
  .key-pad.root-key .key-note { color: #f0c27b; font-weight: 700; }
  .key-pad.root-key:active, .key-pad.root-key.pressed { background: rgba(212, 163, 89, 0.3); }

  .key-pad.third-key {
    border: 1.5px dashed rgba(212, 163, 89, 0.75);
    box-shadow: 0 0 6px rgba(212, 163, 89, 0.25), inset 0 0 4px rgba(212, 163, 89, 0.1);
  }
  .key-pad.third-key .key-note { color: rgba(212, 163, 89, 0.9); font-weight: 600; }
  .key-pad.third-key:active, .key-pad.third-key.pressed { background: rgba(212, 163, 89, 0.2); }

  .key-pad.fifth-key {
    border-color: rgba(212, 163, 89, 0.45);
    box-shadow: 0 0 4px rgba(212, 163, 89, 0.15);
  }
  .key-pad.fifth-key .key-note { color: rgba(212, 163, 89, 0.75); font-weight: 500; }
  .key-pad.fifth-key:active, .key-pad.fifth-key.pressed { background: rgba(212, 163, 89, 0.15); }

  .key-pad.control-pad {
    background: rgba(30, 26, 23, 0.95);
    border-color: rgba(55, 48, 42, 1.0);
  }

  .key-pad.control-pad .key-note {
    color: #a09588;
    font-size: 9.5px;
  }

  .key-pad.mode-control {
    background: rgba(45, 38, 30, 0.95);
    border-color: rgba(212, 163, 89, 0.55);
  }

  .key-pad.mode-control .key-note {
    color: #d4a359;
    font-weight: 600;
  }

  .key-pad.sustain-active {
    background: rgba(212, 163, 89, 0.25);
    border-color: #d4a359;
  }

  .key-pad.sustain-active .key-note {
    color: #d4a359;
    font-weight: 600;
  }
</style>
</head>
<body style="--mod-intensity: 0;">
  <div id="hud-container">
    <div class="mod-gradient-overlay"></div>
    <div id="spotlight-card" class="spotlight-card hidden">
      <div id="spotlight-title" class="spotlight-title"></div>
      <div id="spotlight-val" class="spotlight-val"></div>
      <div id="spotlight-sub" class="spotlight-sub"></div>
    </div>
    <div id="header">
      <select id="root-select" class="badge">
        <option value="0">C</option>
        <option value="1">C#</option>
        <option value="2">D</option>
        <option value="3">D#</option>
        <option value="4">E</option>
        <option value="5">F</option>
        <option value="6">F#</option>
        <option value="7">G</option>
        <option value="8">G#</option>
        <option value="9">A</option>
        <option value="10">A#</option>
        <option value="11">B</option>
      </select>
      <div class="mode-center-block">
        <div id="mode-track" class="mode-slider-track">
          <div id="mode-thumb" class="mode-slider-thumb"></div>
        </div>
        <div id="mode-name" class="mode-name-label">Major / Ionian</div>
      </div>
      <button id="arp-power-btn" class="arp-btn">ARP: OFF</button>
      <select id="arp-dir-select" class="badge-small" title="Arp Direction">
        <option value="1">UP</option>
        <option value="2">DOWN</option>
        <option value="3">UP-DN</option>
        <option value="4">RND</option>
      </select>
      <select id="arp-rate-select" class="badge-small" title="Arp Time Division">
        <option value="1">1/4</option>
        <option value="2" selected>1/8</option>
        <option value="3">1/16</option>
        <option value="4">1/32</option>
        <option value="5">1/8T</option>
        <option value="6">1/16T</option>
      </select>
      <select id="arp-gate-select" class="badge-small" title="Arp Note Length / Gate">
        <option value="1">25%</option>
        <option value="2">50%</option>
        <option value="3" selected>80%</option>
        <option value="4">100%</option>
      </select>
      <div id="bpm-editor" class="bpm-editor">
        <button id="bpm-down" class="bpm-arrow-btn">&#9662;</button>
        <span id="bpm-value" class="bpm-display">120 BPM</span>
        <button id="bpm-up" class="bpm-arrow-btn">&#9652;</button>
      </div>
      <div id="status-text" class="status-info"></div>
    </div>
    
    <div class="keyboard-grid">
      <div id="row-number" class="keyboard-row number"></div>
      <div class="row-with-indicator">
        <div id="row-upper" class="keyboard-row upper"></div>
        <div class="row-controls">
          <button id="arp-top-toggle" class="arp-row-toggle active">ARP</button>
          <div id="octave-indicator-top" class="octave-row-badge draggable-octave" data-row="top">TOP +1</div>
          <div id="vol-indicator-top" class="octave-row-badge" title="Top Row Volume">VOL 79%</div>
        </div>
      </div>
      <div id="row-home" class="keyboard-row home"></div>
      <div class="row-with-indicator">
        <div id="row-lower" class="keyboard-row lower"></div>
        <div class="row-controls">
          <button id="arp-bottom-toggle" class="arp-row-toggle active">ARP</button>
          <div id="octave-indicator-bottom" class="octave-row-badge draggable-octave" data-row="bottom">OCT 0</div>
          <div id="vol-indicator-bottom" class="octave-row-badge" title="Bottom Row Volume">VOL 79%</div>
        </div>
      </div>
    </div>
  </div>

<script>
  const LAYOUT_DATA = {
    number: [
      { code: 18, keyLabel: "1", isControl: true, noteLabel: "TopOct -" },
      { code: 19, keyLabel: "2", isControl: true, noteLabel: "TopOct +" },
      { code: 20, keyLabel: "3", isControl: true, noteLabel: "Trnsp -" },
      { code: 21, keyLabel: "4", isControl: true, noteLabel: "Trnsp +" },
      { code: 23, keyLabel: "5", isControl: true, noteLabel: "Oct -" },
      { code: 22, keyLabel: "6", isControl: true, noteLabel: "Oct +" },
      { code: 26, keyLabel: "7", isControl: true, noteLabel: "Mode -" },
      { code: 28, keyLabel: "8", isControl: true, noteLabel: "Mode +" },
      { code: 25, keyLabel: "9", isControl: true, noteLabel: "Panic" },
      { code: 29, keyLabel: "0", isControl: true, noteLabel: "Reset" },
      { code: 27, keyLabel: "-", isControl: true, noteLabel: "Zoom -" },
      { code: 24, keyLabel: "=", isControl: true, noteLabel: "Zoom +" }
    ],
    upper: [
      { code: 12, keyLabel: "Q" }, { code: 13, keyLabel: "W" }, { code: 14, keyLabel: "E" },
      { code: 15, keyLabel: "R" }, { code: 17, keyLabel: "T" }, { code: 16, keyLabel: "Y" },
      { code: 32, keyLabel: "U" }, { code: 34, keyLabel: "I" }, { code: 31, keyLabel: "O" }, { code: 35, keyLabel: "P" }
    ],
    home: [
      { code: 0,  keyLabel: "A", isControl: true, noteLabel: "Sustain" },
      { code: 1,  keyLabel: "S", isControl: true, noteLabel: "Random" },
      { code: 2,  keyLabel: "D", isControl: true, noteLabel: "Oct -" },
      { code: 3,  keyLabel: "F", isControl: true, noteLabel: "Oct +" },
      { code: 5,  keyLabel: "G", isControl: true, noteLabel: "Vol -" },
      { code: 4,  keyLabel: "H", isControl: true, noteLabel: "Root -" },
      { code: 38, keyLabel: "J", isControl: true, noteLabel: "Mode -" },
      { code: 40, keyLabel: "K", isControl: true, noteLabel: "Mode +" },
      { code: 37, keyLabel: "L", isControl: true, noteLabel: "Root +" },
      { code: 41, keyLabel: ";", isControl: true, noteLabel: "Vol +" }
    ],
    lower: [
      { code: 6,  keyLabel: "Z" }, { code: 7,  keyLabel: "X" }, { code: 8,  keyLabel: "C" },
      { code: 9,  keyLabel: "V" }, { code: 11, keyLabel: "B" }, { code: 45, keyLabel: "N" },
      { code: 46, keyLabel: "M" }, { code: 43, keyLabel: "," }, { code: 47, keyLabel: "." }, { code: 44, keyLabel: "/" }
    ]
  };

  let spotlightTimer1 = null;
  let spotlightTimer2 = null;

  let isDragging = false;
  let dragStartX = 0;
  let dragStartY = 0;

  const activeClickedPads = new Set();
  
  let octaveDragTarget = null;
  let octaveDragStartY = 0;
  let octaveDragAccum = 0;

  let bpmBtnTimer = null;
  let bpmBtnInterval = null;
  let bpmBtnStartTime = 0;
  let bpmBtnDirection = 0;

  let isBpmDragging = false;
  let bpmDragStartY = 0;
  let bpmDragAccum = 0;

  function initGrid(layout) {
    const l = layout || LAYOUT_DATA;
    ['number', 'upper', 'home', 'lower'].forEach(rowName => {
      const rowEl = document.getElementById('row-' + rowName);
      if (!rowEl) return;
      rowEl.innerHTML = '';
      if (l[rowName]) {
        l[rowName].forEach(k => {
          const pad = document.createElement('div');
          pad.id = 'key-' + k.code;
          pad.className = 'key-pad ' + (k.isControl ? 'control-pad' : '');
          
          const codeSpan = document.createElement('span');
          codeSpan.className = 'key-code';
          codeSpan.textContent = k.keyLabel;
          
          const noteSpan = document.createElement('span');
          noteSpan.className = 'key-note';
          noteSpan.textContent = k.noteLabel || '';
          
          pad.appendChild(codeSpan);
          pad.appendChild(noteSpan);

          pad.addEventListener('mousedown', (e) => {
            e.stopPropagation();
            activeClickedPads.add(k.code);
            if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.midiControllerUC) {
              window.webkit.messageHandlers.midiControllerUC.postMessage({ type: 'keyDown', code: k.code });
            }
          });

          const releasePad = (e) => {
            if (activeClickedPads.has(k.code)) {
              activeClickedPads.delete(k.code);
              if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.midiControllerUC) {
                window.webkit.messageHandlers.midiControllerUC.postMessage({ type: 'keyUp', code: k.code });
              }
            }
          };

          pad.addEventListener('mouseup', releasePad);
          pad.addEventListener('mouseleave', releasePad);

          rowEl.appendChild(pad);
        });
      }
    });
  }

  let isModeDragging = false;
  const SCALES_COUNT = 9;

  function handleModeSliderEvent(e) {
    const modeTrack = document.getElementById('mode-track');
    if (!modeTrack) return;
    const rect = modeTrack.getBoundingClientRect();
    let frac = (e.clientX - rect.left) / rect.width;
    frac = Math.max(0, Math.min(1, frac));
    
    const modeIdx = Math.min(SCALES_COUNT, Math.max(1, Math.floor(frac * SCALES_COUNT) + 1));
    
    const snappedFrac = (modeIdx - 0.5) / SCALES_COUNT;
    const thumb = document.getElementById('mode-thumb');
    if (thumb) thumb.style.left = (snappedFrac * 100) + '%';
    
    if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.midiControllerUC) {
      window.webkit.messageHandlers.midiControllerUC.postMessage({ type: 'setModeIdx', modeIdx: modeIdx });
    }
  }

  // Auto-initialize grid instantly on document load and notify Lua host
  window.addEventListener('DOMContentLoaded', () => {
    initGrid(LAYOUT_DATA);

    if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.midiControllerUC) {
      window.webkit.messageHandlers.midiControllerUC.postMessage({ type: 'domReady' });
    }

    const container = document.getElementById('hud-container');
    if (container) {
      container.addEventListener('mousedown', (e) => {
        if (e.target.closest('.key-pad') || e.target.closest('select') || e.target.closest('button') || e.target.closest('.mode-center-block') || e.target.closest('.bpm-editor')) return;
        isDragging = true;
        dragStartX = e.screenX;
        dragStartY = e.screenY;
      });
    }

    const rootSelect = document.getElementById('root-select');
    if (rootSelect) {
      rootSelect.addEventListener('change', (e) => {
        const val = parseInt(e.target.value);
        if (!isNaN(val) && window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.midiControllerUC) {
          window.webkit.messageHandlers.midiControllerUC.postMessage({ type: 'setRoot', root: val });
        }
      });
      rootSelect.addEventListener('mousedown', (e) => e.stopPropagation());
    }

    const modeTrack = document.getElementById('mode-track');
    if (modeTrack) {
      modeTrack.addEventListener('mousedown', (e) => {
        e.stopPropagation();
        isModeDragging = true;
        handleModeSliderEvent(e);
      });
    }

    const arpPowerBtn = document.getElementById('arp-power-btn');
    if (arpPowerBtn) {
      arpPowerBtn.addEventListener('click', (e) => {
        e.stopPropagation();
        if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.midiControllerUC) {
          window.webkit.messageHandlers.midiControllerUC.postMessage({ type: 'toggleArpPower' });
        }
      });
    }

    const arpDirSelect = document.getElementById('arp-dir-select');
    if (arpDirSelect) {
      arpDirSelect.addEventListener('change', (e) => {
        const val = parseInt(e.target.value);
        if (!isNaN(val) && window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.midiControllerUC) {
          window.webkit.messageHandlers.midiControllerUC.postMessage({ type: 'setArpDirection', directionIdx: val });
        }
      });
      arpDirSelect.addEventListener('mousedown', (e) => e.stopPropagation());
    }

    const arpRateSelect = document.getElementById('arp-rate-select');
    if (arpRateSelect) {
      arpRateSelect.addEventListener('change', (e) => {
        const val = parseInt(e.target.value);
        if (!isNaN(val) && window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.midiControllerUC) {
          window.webkit.messageHandlers.midiControllerUC.postMessage({ type: 'setArpRate', rateIdx: val });
        }
      });
      arpRateSelect.addEventListener('mousedown', (e) => e.stopPropagation());
    }

    const arpGateSelect = document.getElementById('arp-gate-select');
    if (arpGateSelect) {
      arpGateSelect.addEventListener('change', (e) => {
        const val = parseInt(e.target.value);
        if (!isNaN(val) && window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.midiControllerUC) {
          window.webkit.messageHandlers.midiControllerUC.postMessage({ type: 'setArpGate', gateIdx: val });
        }
      });
      arpGateSelect.addEventListener('mousedown', (e) => e.stopPropagation());
    }

    // BPM Editor handlers
    let hasBpmDragged = false;
    const bpmValue = document.getElementById('bpm-value');
    if (bpmValue) {
      bpmValue.style.cursor = 'ns-resize';
      bpmValue.addEventListener('mousedown', (e) => {
        e.stopPropagation();
        e.preventDefault();
        isBpmDragging = true;
        hasBpmDragged = false;
        bpmDragStartY = e.clientY;
        bpmDragAccum = 0;
      });
      bpmValue.addEventListener('click', (e) => {
        e.stopPropagation();
        if (!hasBpmDragged) {
          if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.midiControllerUC) {
            window.webkit.messageHandlers.midiControllerUC.postMessage({ type: 'enterBpmEdit' });
          }
        }
      });
    }

    function stopBpmRepeat() {
      if (bpmBtnTimer) { clearTimeout(bpmBtnTimer); bpmBtnTimer = null; }
      if (bpmBtnInterval) { clearInterval(bpmBtnInterval); bpmBtnInterval = null; }
      bpmBtnDirection = 0;
    }

    function startBpmRepeat(direction) {
      stopBpmRepeat();
      bpmBtnDirection = direction;
      bpmBtnStartTime = Date.now();
      const sendStep = () => {
        if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.midiControllerUC) {
          window.webkit.messageHandlers.midiControllerUC.postMessage({
            type: bpmBtnDirection > 0 ? 'bpmUp' : 'bpmDown'
          });
        }
      };
      sendStep();

      bpmBtnTimer = setTimeout(() => {
        bpmBtnInterval = setInterval(() => {
          const elapsed = Date.now() - bpmBtnStartTime;
          let repeats = 1;
          if (elapsed > 3000) repeats = 5;
          else if (elapsed > 1500) repeats = 3;
          else if (elapsed > 700) repeats = 2;

          for (let i = 0; i < repeats; i++) {
            sendStep();
          }
        }, 80);
      }, 350);
    }

    ['bpm-up', 'bpm-down'].forEach(id => {
      const btn = document.getElementById(id);
      if (btn) {
        const dir = id === 'bpm-up' ? 1 : -1;
        btn.addEventListener('mousedown', (e) => {
          e.stopPropagation();
          e.preventDefault();
          startBpmRepeat(dir);
        });
        btn.addEventListener('mouseleave', stopBpmRepeat);
      }
    });

    // Arp Row Toggle handlers
    const arpTopToggle = document.getElementById('arp-top-toggle');
    if (arpTopToggle) {
      arpTopToggle.addEventListener('click', (e) => {
        e.stopPropagation();
        if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.midiControllerUC) {
          window.webkit.messageHandlers.midiControllerUC.postMessage({ type: 'toggleArpTop' });
        }
      });
    }
    const arpBottomToggle = document.getElementById('arp-bottom-toggle');
    if (arpBottomToggle) {
      arpBottomToggle.addEventListener('click', (e) => {
        e.stopPropagation();
        if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.midiControllerUC) {
          window.webkit.messageHandlers.midiControllerUC.postMessage({ type: 'toggleArpBottom' });
        }
      });
    }

    // Draggable Octave Indicators
    document.querySelectorAll('.draggable-octave').forEach(el => {
      el.addEventListener('mousedown', (e) => {
        e.stopPropagation();
        e.preventDefault();
        octaveDragTarget = el.dataset.row;
        octaveDragStartY = e.clientY;
        octaveDragAccum = 0;
      });
    });
  });

  window.addEventListener('mousemove', (e) => {
    if (isBpmDragging) {
      const dy = bpmDragStartY - e.clientY;
      bpmDragAccum += dy;
      bpmDragStartY = e.clientY;
      const stepThreshold = e.shiftKey ? 3 : 8;
      if (Math.abs(bpmDragAccum) >= stepThreshold) {
        hasBpmDragged = true;
        const steps = Math.trunc(bpmDragAccum / stepThreshold);
        bpmDragAccum %= stepThreshold;
        if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.midiControllerUC) {
          window.webkit.messageHandlers.midiControllerUC.postMessage({
            type: 'dragBpm',
            delta: steps
          });
        }
      }
      return;
    }
    if (octaveDragTarget) {
      const dy = octaveDragStartY - e.clientY;
      octaveDragAccum += dy;
      octaveDragStartY = e.clientY;
      if (Math.abs(octaveDragAccum) >= 30) {
        const direction = octaveDragAccum > 0 ? 1 : -1;
        octaveDragAccum = 0;
        if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.midiControllerUC) {
          window.webkit.messageHandlers.midiControllerUC.postMessage({
            type: 'dragOctave',
            row: octaveDragTarget,
            direction: direction
          });
        }
      }
      return;
    }
    if (isModeDragging) {
      handleModeSliderEvent(e);
      return;
    }
    if (!isDragging) return;
    const dx = e.screenX - dragStartX;
    const dy2 = e.screenY - dragStartY;
    dragStartX = e.screenX;
    dragStartY = e.screenY;
    if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.midiControllerUC) {
      window.webkit.messageHandlers.midiControllerUC.postMessage({ type: 'dragWindow', dx: dx, dy: dy2 });
    }
  });

  window.addEventListener('mouseup', () => {
    isDragging = false;
    isModeDragging = false;
    octaveDragTarget = null;
    isBpmDragging = false;
    stopBpmRepeat();
  });

  function showSpotlight(spotlight) {
    if (!spotlight) return;
    const card = document.getElementById('spotlight-card');
    const titleEl = document.getElementById('spotlight-title');
    const valEl = document.getElementById('spotlight-val');
    const subEl = document.getElementById('spotlight-sub');
    if (!card || !valEl) return;

    if (spotlightTimer1) clearTimeout(spotlightTimer1);
    if (spotlightTimer2) clearTimeout(spotlightTimer2);

    titleEl.textContent = spotlight.title || '';
    valEl.textContent = spotlight.value || '';
    subEl.textContent = spotlight.subtext || '';

    const color = spotlight.color || '#d4a359';
    card.style.borderColor = color;
    card.style.boxShadow = '0 4px 20px rgba(0,0,0,0.85), 0 0 15px ' + color + '66';
    subEl.style.color = color;

    card.classList.remove('hidden');
    card.style.transition = 'none';
    card.style.opacity = '1';
    card.style.transform = 'translate(-50%, -100%) scale(1.0)';
    card.style.left = '50%';
    card.style.top = '-5px';

    card.offsetHeight;

    card.style.transition = 'opacity 0.4s ease, transform 0.4s ease';

    spotlightTimer1 = setTimeout(() => {
      card.style.opacity = '0';
      card.style.transform = 'translate(-50%, -100%) scale(0.85)';

      spotlightTimer2 = setTimeout(() => {
        card.classList.add('hidden');
      }, 400);
    }, 1000);
  }

  function renderHud(data) {
    if (!data) return;

    if (data.zoomLevel !== undefined) {
      const container = document.getElementById('hud-container');
      if (container) {
        const targetTransform = 'scale(' + data.zoomLevel + ')';
        if (container.style.transform !== targetTransform) {
          container.style.transform = targetTransform;
        }
      }
    }

    if (data.spotlight) {
      showSpotlight(data.spotlight);
    }
    
    if (data.rootIdx !== undefined) {
      const rootSelect = document.getElementById('root-select');
      if (rootSelect) rootSelect.value = data.rootIdx;
    }
    
    if (data.modeName) {
      document.getElementById('mode-name').textContent = data.modeName;
    }

    if (data.arpEnabled !== undefined) {
      const arpPowerBtn = document.getElementById('arp-power-btn');
      if (arpPowerBtn) {
        arpPowerBtn.textContent = data.arpEnabled ? 'ARP: ON' : 'ARP: OFF';
        if (data.arpEnabled) {
          arpPowerBtn.classList.add('arp-active');
        } else {
          arpPowerBtn.classList.remove('arp-active');
        }
      }
    }

    if (data.arpDirectionIdx !== undefined) {
      const arpDirSelect = document.getElementById('arp-dir-select');
      if (arpDirSelect) arpDirSelect.value = data.arpDirectionIdx;
    }

    if (data.arpRateIdx !== undefined) {
      const arpRateSelect = document.getElementById('arp-rate-select');
      if (arpRateSelect) arpRateSelect.value = data.arpRateIdx;
    }

    if (data.arpGateIdx !== undefined) {
      const arpGateSelect = document.getElementById('arp-gate-select');
      if (arpGateSelect) arpGateSelect.value = data.arpGateIdx;
    }

    if (data.bpmDisplay !== undefined) {
      const bpmVal = document.getElementById('bpm-value');
      if (bpmVal) {
        bpmVal.textContent = data.bpmDisplay;
        if (data.bpmEditing) {
          bpmVal.classList.add('editing');
        } else {
          bpmVal.classList.remove('editing');
        }
      }
    }

    if (data.arpTopEnabled !== undefined) {
      const topToggle = document.getElementById('arp-top-toggle');
      if (topToggle) {
        if (data.arpTopEnabled) topToggle.classList.add('active');
        else topToggle.classList.remove('active');
      }
    }

    if (data.arpBottomEnabled !== undefined) {
      const botToggle = document.getElementById('arp-bottom-toggle');
      if (botToggle) {
        if (data.arpBottomEnabled) botToggle.classList.add('active');
        else botToggle.classList.remove('active');
      }
    }

    if (data.statusText !== undefined) {
      document.getElementById('status-text').textContent = data.statusText;
    }

    if (data.topOctaveStr !== undefined) {
      const topEl = document.getElementById('octave-indicator-top');
      if (topEl) topEl.textContent = 'TOP ' + data.topOctaveStr;
    }

    if (data.bottomOctaveStr !== undefined) {
      const botEl = document.getElementById('octave-indicator-bottom');
      if (botEl) botEl.textContent = 'OCT ' + data.bottomOctaveStr;
    }

    if (data.topVolPercent !== undefined) {
      const topVolEl = document.getElementById('vol-indicator-top');
      if (topVolEl) {
        if (data.effectiveTopVolPercent !== undefined && data.effectiveTopVolPercent !== data.topVolPercent) {
          topVolEl.textContent = 'VOL ' + data.effectiveTopVolPercent + '% (🚀)';
        } else {
          topVolEl.textContent = 'VOL ' + data.topVolPercent + '%';
        }
      }
    }

    if (data.bottomVolPercent !== undefined) {
      const botVolEl = document.getElementById('vol-indicator-bottom');
      if (botVolEl) botVolEl.textContent = 'VOL ' + data.bottomVolPercent + '%';
    }

    if (data.modeFrac !== undefined && !isModeDragging) {
      document.getElementById('mode-thumb').style.left = (data.modeFrac * 100) + '%';
    }

    if (data.modWheel !== undefined) {
      const intensity = (data.modWheel / 127.0).toFixed(2);
      document.body.style.setProperty('--mod-intensity', intensity);
      const container = document.getElementById('hud-container');
      if (data.modWheel > 0) {
        container.classList.add('mod-active');
      } else {
        container.classList.remove('mod-active');
      }
    }

    if (data.keys) {
      for (const [code, k] of Object.entries(data.keys)) {
        const el = document.getElementById('key-' + code);
        if (el) {
          const noteEl = el.querySelector('.key-note');
          if (noteEl && k.note !== undefined) {
            noteEl.textContent = k.note;
          }
          
          el.className = 'key-pad ' + (k.isControl ? 'control-pad ' : '') + (k.typeClass || '');
          if (k.pressed) el.classList.add('pressed');
          if (k.sustainActive) el.classList.add('sustain-active');
        }
      }
    }
  }

  // Immediate init execution in case DOM ready state passed
  initGrid(LAYOUT_DATA);
</script>
</body>
</html>
]]

return HTML_UI_CONTENT

end

__modules["config"] = function()
local state = {
  midiActive = false,
  currentRoot = 0,            -- 0 = C (0..11)
  currentScaleIdx = 1,        -- 1 = Major / Ionian
  octaveShift = 0,            -- Global Octave offset in semitones (-36 to +36)
  topRowOctaveOffset = 0,     -- Independent Top Row Octave Offset
  transposeShift = 0,         -- Transpose offset in semitones (-12 to +12)
  sustainActive = false,      -- Sustain / Latch mode toggle state (CC64)
  sustainKeyDownTime = 0,     -- Timestamp when sustain key was pressed down
  sustainWasActiveOnPress = false,
  shiftHeld = false,          -- Shift key active state
  zoomLevel = hs.settings.get("qwertyMidi_zoomLevel") or 1.0,
  BASE_HUD_SCALE = 1.4,

  -- Arpeggiator State
  arpEnabled = false,
  arpDirectionIdx = 1,        -- 1: UP, 2: DOWN, 3: UP-DOWN, 4: RANDOM
  ARP_DIRECTIONS = { "UP", "DOWN", "UP-DOWN", "RANDOM" },
  arpRateIdx = 2,
  ARP_RATES = {
    { label = "1/4", factor = 1.0 },
    { label = "1/8", factor = 0.5 },
    { label = "1/16", factor = 0.25 },
    { label = "1/32", factor = 0.125 },
    { label = "1/8T", factor = 1.0 / 3.0 },
    { label = "1/16T", factor = 0.5 / 3.0 }
  },
  arpGateIdx = 3,
  ARP_GATES = {
    { label = "25%", ratio = 0.25 },
    { label = "50%", ratio = 0.50 },
    { label = "80%", ratio = 0.80 },
    { label = "100%", ratio = 1.00 }
  },
  arpBpm = 120.0,
  arpTimer = nil,
  arpGateTimer = nil,
  arpHeldNotes = {},          -- [code] = pitch
  arpKeysCurrentlyHeld = {},  -- [code] = true
  arpCurrentPitch = nil,
  arpStepIndex = 1,
  arpStepDirection = 1,
  lastArpMode = 1,
  arpTopEnabled = false,
  arpBottomEnabled = true,

  -- BPM Input Mode State
  bpmInputMode = false,
  bpmInputBuffer = "",
  bpmBeforeEdit = 120.0,

  DIGIT_KEYCODES = {
    [29] = "0", [18] = "1", [19] = "2", [20] = "3", [21] = "4",
    [23] = "5", [22] = "6", [26] = "7", [28] = "8", [25] = "9"
  },

  topRowVolume = 100,
  bottomRowVolume = 100,
  splitArpTopBoost = 20,

  ccStates = {
    [1] = 0,
    [7] = 100
  },

  pressedKeys = {},
  spotlightInfo = nil
}

local SCALES = {
  { name = "Lydian",                  intervals = { 0, 2, 4, 6, 7, 9, 11 }, brightness = 6, brightTag = "BRIGHTEST ☀️" },
  { name = "Major / Ionian",          intervals = { 0, 2, 4, 5, 7, 9, 11 }, brightness = 5, brightTag = "BRIGHT 🌤" },
  { name = "Mixolydian",              intervals = { 0, 2, 4, 5, 7, 9, 10 }, brightness = 4, brightTag = "WARM ⛅" },
  { name = "Dorian",                  intervals = { 0, 2, 3, 5, 7, 9, 10 }, brightness = 3, brightTag = "NEUTRAL ☁️" },
  { name = "Natural Minor / Aeolian", intervals = { 0, 2, 3, 5, 7, 8, 10 }, brightness = 2, brightTag = "DARK 🌧" },
  { name = "Phrygian",                intervals = { 0, 1, 3, 5, 7, 8, 10 }, brightness = 1, brightTag = "DARKER 🌩" },
  { name = "Locrian",                 intervals = { 0, 1, 3, 5, 6, 8, 10 }, brightness = 0, brightTag = "DARKEST 🌑" },
  { name = "Harmonic Minor",          intervals = { 0, 2, 3, 5, 7, 8, 11 }, brightness = 2, brightTag = "EXOTIC 🔮" },
  { name = "Melodic Minor",           intervals = { 0, 2, 3, 5, 7, 9, 11 }, brightness = 3, brightTag = "JAZZY 🎷" }
}

local NOTE_NAMES = { "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B" }

local WHITE_KEY_INDEX = {
  [0] = 0, [1] = -1, [2] = 1, [3] = -1, [4] = 2, [5] = 3,
  [6] = -1, [7] = 4, [8] = -1, [9] = 5, [10] = -1, [11] = 6
}

local numberRowControls = {
  [18] = { key = "1", name = "TopOct -", action = "topOctDown" },
  [19] = { key = "2", name = "TopOct +", action = "topOctUp" },
  [20] = { key = "3", name = "Trnsp -",  action = "trnspDown" },
  [21] = { key = "4", name = "Trnsp +",  action = "trnspUp" },
  [23] = { key = "5", name = "Oct -",    action = "octaveDown" },
  [22] = { key = "6", name = "Oct +",    action = "octaveUp" },
  [26] = { key = "7", name = "Mode -",   action = "modeDown" },
  [28] = { key = "8", name = "Mode +",   action = "modeUp" },
  [25] = { key = "9", name = "Panic",    action = "panic" },
  [29] = { key = "0", name = "Reset",    action = "resetAll" },
  [27] = { key = "-", name = "Zoom -",   action = "zoomOut" },
  [24] = { key = "=", name = "Zoom +",   action = "zoomIn" }
}

local lowerRowKeys = {
  [6]  = { key = "Z", baseNote = 60 },
  [7]  = { key = "X", baseNote = 62 },
  [8]  = { key = "C", baseNote = 64 },
  [9]  = { key = "V", baseNote = 65 },
  [11] = { key = "B", baseNote = 67 },
  [45] = { key = "N", baseNote = 69 },
  [46] = { key = "M", baseNote = 71 },
  [43] = { key = ",", baseNote = 72 },
  [47] = { key = ".", baseNote = 74 },
  [44] = { key = "/", baseNote = 76 }
}

local upperRowKeys = {
  [12] = { key = "Q", baseNote = 72 },
  [13] = { key = "W", baseNote = 74 },
  [14] = { key = "E", baseNote = 76 },
  [15] = { key = "R", baseNote = 77 },
  [17] = { key = "T", baseNote = 79 },
  [16] = { key = "Y", baseNote = 81 },
  [32] = { key = "U", baseNote = 83 },
  [34] = { key = "I", baseNote = 84 },
  [31] = { key = "O", baseNote = 86 },
  [35] = { key = "P", baseNote = 88 }
}

local homeRowControls = {
  [48] = { key = "Tab", name = "Sustain", action = "sustain",     shiftAction = "resetAll",   shiftName = "Reset" },
  [0]  = { key = "A",   name = "Sustain", action = "sustain",     shiftAction = "resetAll",   shiftName = "Reset" },
  [1]  = { key = "S",   name = "Random",  action = "randomScale", shiftAction = "panic",      shiftName = "Panic!" },
  [2]  = { key = "D",   name = "Oct -",   action = "octaveDown",  shiftAction = "topOctDown", shiftName = "TopOct -" },
  [3]  = { key = "F",   name = "Oct +",   action = "octaveUp",    shiftAction = "topOctUp",   shiftName = "TopOct +" },
  [5]  = { key = "G",   name = "Vol -",   action = "volDown",     shiftAction = "volDown",    shiftName = "Vol -" },
  [4]  = { key = "H",   name = "Root -",  action = "rootDown",    shiftAction = "topOctDown", shiftName = "TopOct -" },
  [38] = { key = "J",   name = "Mode -",  action = "modeDown",    shiftAction = "modWheelDown", shiftName = "Mod -" },
  [40] = { key = "K",   name = "Mode +",  action = "modeUp",      shiftAction = "modWheelUp",   shiftName = "Mod +" },
  [37] = { key = "L",   name = "Root +",  action = "rootUp",      shiftAction = "topOctUp",   shiftName = "TopOct +" },
  [41] = { key = ";",   name = "Vol +",   action = "volUp",       shiftAction = "volUp",      shiftName = "Vol +" }
}

return {
  state = state,
  SCALES = SCALES,
  NOTE_NAMES = NOTE_NAMES,
  WHITE_KEY_INDEX = WHITE_KEY_INDEX,
  numberRowControls = numberRowControls,
  lowerRowKeys = lowerRowKeys,
  upperRowKeys = upperRowKeys,
  homeRowControls = homeRowControls
}

end

__modules["controls"] = function()
local config = __require("config")
local midi = __require("midi")
local transposer = __require("transposer")
local arpeggiator = __require("arpeggiator")
local hud = __require("hud")

local state = config.state
local SCALES = config.SCALES
local NOTE_NAMES = config.NOTE_NAMES
local numberRowControls = config.numberRowControls
local upperRowKeys = config.upperRowKeys
local lowerRowKeys = config.lowerRowKeys
local homeRowControls = config.homeRowControls

_G.activeWatchers = _G.activeWatchers or {}

local function executeControlAction(act, code)
  if act == "topOctDown" then
    state.topRowOctaveOffset = math.max(-36, state.topRowOctaveOffset - 12)
    local spot = {
      title = "TOP ROW OCTAVE",
      value = (state.topRowOctaveOffset >= 0 and "+" or "") .. math.floor(state.topRowOctaveOffset / 12) .. " Oct",
      subtext = "Upper Row Pitch",
      targetId = "octave-indicator-top",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "topOctUp" then
    state.topRowOctaveOffset = math.min(36, state.topRowOctaveOffset + 12)
    local spot = {
      title = "TOP ROW OCTAVE",
      value = (state.topRowOctaveOffset >= 0 and "+" or "") .. math.floor(state.topRowOctaveOffset / 12) .. " Oct",
      subtext = "Upper Row Pitch",
      targetId = "octave-indicator-top",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "trnspDown" then
    state.transposeShift = math.max(-12, state.transposeShift - 1)
    local spot = {
      title = "TRANSPOSE",
      value = (state.transposeShift >= 0 and "+" or "") .. state.transposeShift .. " st",
      subtext = "Semitone Shift",
      targetId = "status-text",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "trnspUp" then
    state.transposeShift = math.min(12, state.transposeShift + 1)
    local spot = {
      title = "TRANSPOSE",
      value = (state.transposeShift >= 0 and "+" or "") .. state.transposeShift .. " st",
      subtext = "Semitone Shift",
      targetId = "status-text",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "octaveDown" then
    state.octaveShift = math.max(-36, state.octaveShift - 12)
    local spot = {
      title = "GLOBAL OCTAVE",
      value = (state.octaveShift >= 0 and "+" or "") .. math.floor(state.octaveShift / 12) .. " Oct",
      subtext = "Global Pitch Offset",
      targetId = "octave-indicator-bottom",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "octaveUp" then
    state.octaveShift = math.min(36, state.octaveShift + 12)
    local spot = {
      title = "GLOBAL OCTAVE",
      value = (state.octaveShift >= 0 and "+" or "") .. math.floor(state.octaveShift / 12) .. " Oct",
      subtext = "Global Pitch Offset",
      targetId = "octave-indicator-bottom",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "modeDown" then
    state.currentScaleIdx = (state.currentScaleIdx - 2) % #SCALES + 1
    arpeggiator.updateLatchedArpNotes()
    local scaleInfo = SCALES[state.currentScaleIdx]
    local spot = {
      title = "SCALE / MODE",
      value = scaleInfo.name,
      subtext = scaleInfo.brightTag,
      targetId = "mode-thumb",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "modeUp" then
    state.currentScaleIdx = (state.currentScaleIdx % #SCALES) + 1
    arpeggiator.updateLatchedArpNotes()
    local scaleInfo = SCALES[state.currentScaleIdx]
    local spot = {
      title = "SCALE / MODE",
      value = scaleInfo.name,
      subtext = scaleInfo.brightTag,
      targetId = "mode-thumb",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "rootDown" then
    if state.currentRoot == 0 then
      state.currentRoot = 11
      state.octaveShift = math.max(-36, state.octaveShift - 12)
    else
      state.currentRoot = state.currentRoot - 1
    end
    arpeggiator.updateLatchedArpNotes()
    local rootName = NOTE_NAMES[state.currentRoot + 1]
    local spot = {
      title = "ROOT NOTE",
      value = rootName,
      subtext = rootName .. " " .. SCALES[state.currentScaleIdx].name,
      targetId = "root-select",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "rootUp" then
    if state.currentRoot == 11 then
      state.currentRoot = 0
      state.octaveShift = math.min(36, state.octaveShift + 12)
    else
      state.currentRoot = state.currentRoot + 1
    end
    arpeggiator.updateLatchedArpNotes()
    local rootName = NOTE_NAMES[state.currentRoot + 1]
    local spot = {
      title = "ROOT NOTE",
      value = rootName,
      subtext = rootName .. " " .. SCALES[state.currentScaleIdx].name,
      targetId = "root-select",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "randomScale" then
    state.currentRoot = math.random(0, 11)
    state.currentScaleIdx = math.random(1, #SCALES)
    arpeggiator.updateLatchedArpNotes()
    local rootName = NOTE_NAMES[state.currentRoot + 1]
    local scaleInfo = SCALES[state.currentScaleIdx]
    local spot = {
      title = "RANDOM SCALE",
      value = rootName .. " " .. scaleInfo.name,
      subtext = scaleInfo.brightTag,
      targetId = "mode-thumb",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "panic" then
    midi.sendMidiCC(123, 0)
    state.pressedKeys = {}
    arpeggiator.stopArpTimer()
    state.arpHeldNotes = {}
    state.arpKeysCurrentlyHeld = {}
    local spot = {
      title = "MIDI PANIC",
      value = "ALL NOTES OFF",
      subtext = "Reset Active Notes",
      targetId = code and ("key-" .. code) or "header",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "resetAll" then
    state.octaveShift = 0
    state.topRowOctaveOffset = 0
    state.transposeShift = 0
    state.topRowVolume = 100
    state.bottomRowVolume = 100
    state.currentRoot = 0
    state.currentScaleIdx = 1
    state.sustainActive = false
    state.ccStates[1] = 0
    _G.activeWatchers.modAccumulator = 0
    arpeggiator.stopArpTimer()
    state.arpHeldNotes = {}
    state.arpKeysCurrentlyHeld = {}
    state.arpEnabled = false
    midi.sendMidiCC(64, 0)
    midi.sendMidiCC(1, 0)
    local spot = {
      title = "RESET ALL",
      value = "DEFAULTS RESTORED",
      subtext = "All Parameters Reset",
      targetId = code and ("key-" .. code) or "header",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "zoomOut" then
    state.zoomLevel = math.max(0.5, state.zoomLevel - 0.1)
    local spot = {
      title = "HUD ZOOM",
      value = math.floor(state.zoomLevel * 100) .. "%",
      subtext = "Scale Factor",
      targetId = "header",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "zoomIn" then
    state.zoomLevel = math.min(2.0, state.zoomLevel + 0.1)
    local spot = {
      title = "HUD ZOOM",
      value = math.floor(state.zoomLevel * 100) .. "%",
      subtext = "Scale Factor",
      targetId = "header",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "sustain" or act == "latch" then
    state.sustainKeyDownTime = hs.timer.secondsSinceEpoch()
    state.sustainWasActiveOnPress = state.sustainActive
    state.sustainActive = true
    midi.sendMidiCC(64, 127)
    local spot = {
      title = "SUSTAIN / LATCH (CC #64)",
      value = "SUSTAIN ON",
      subtext = "Notes & Arp pattern hold",
      targetId = "key-0",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "modWheelDown" then
    local currentVal = state.ccStates[1] or 0
    local newVal = math.max(0, currentVal - 4)
    state.ccStates[1] = newVal
    _G.activeWatchers.modAccumulator = newVal
    midi.sendMidiCC(1, newVal)
    local spot = {
      title = "MOD WHEEL",
      value = math.floor((newVal / 127) * 100) .. "%",
      subtext = "CC #1 Intensity",
      targetId = "header",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "modWheelUp" or act == "modWheel" then
    local currentVal = state.ccStates[1] or 0
    local newVal = math.min(127, currentVal + 4)
    state.ccStates[1] = newVal
    _G.activeWatchers.modAccumulator = newVal
    midi.sendMidiCC(1, newVal)
    local spot = {
      title = "MOD WHEEL",
      value = math.floor((newVal / 127) * 100) .. "%",
      subtext = "CC #1 Intensity",
      targetId = "header",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "topVolDown" then
    state.topRowVolume = math.max(0, state.topRowVolume - 4)
    local spot = {
      title = "TOP ROW VOL",
      value = math.floor((state.topRowVolume / 127) * 100) .. "%",
      subtext = "Upper Keys Level",
      targetId = "vol-indicator-top",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "topVolUp" then
    state.topRowVolume = math.min(127, state.topRowVolume + 4)
    local spot = {
      title = "TOP ROW VOL",
      value = math.floor((state.topRowVolume / 127) * 100) .. "%",
      subtext = "Upper Keys Level",
      targetId = "vol-indicator-top",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "botVolDown" then
    state.bottomRowVolume = math.max(0, state.bottomRowVolume - 4)
    local spot = {
      title = "BOTTOM ROW VOL",
      value = math.floor((state.bottomRowVolume / 127) * 100) .. "%",
      subtext = "Lower Keys Level",
      targetId = "vol-indicator-bottom",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "botVolUp" then
    state.bottomRowVolume = math.min(127, state.bottomRowVolume + 4)
    local spot = {
      title = "BOTTOM ROW VOL",
      value = math.floor((state.bottomRowVolume / 127) * 100) .. "%",
      subtext = "Lower Keys Level",
      targetId = "vol-indicator-bottom",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "volDown" then
    state.topRowVolume = math.max(0, state.topRowVolume - 4)
    state.bottomRowVolume = math.max(0, state.bottomRowVolume - 4)
    local spot = {
      title = "ROW VOLUMES",
      value = "TOP " .. math.floor((state.topRowVolume / 127) * 100) .. "% | BOT " .. math.floor((state.bottomRowVolume / 127) * 100) .. "%",
      subtext = "Dual Row Volume Level",
      targetId = "header",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  elseif act == "volUp" or act == "volume" then
    state.topRowVolume = math.min(127, state.topRowVolume + 4)
    state.bottomRowVolume = math.min(127, state.bottomRowVolume + 4)
    local spot = {
      title = "ROW VOLUMES",
      value = "TOP " .. math.floor((state.topRowVolume / 127) * 100) .. "% | BOT " .. math.floor((state.bottomRowVolume / 127) * 100) .. "%",
      subtext = "Dual Row Volume Level",
      targetId = "header",
      color = "#d4a359"
    }
    hud.updateWebviewHud(spot)
  end
end

local function handleKeyDown(code)
  if code == 50 then -- Backtick
    if not state.pressedKeys[code] then
      state.pressedKeys[code] = true
      arpeggiator.toggleArp()
    end
    return true
  end

  if lowerRowKeys[code] then
    local kData = lowerRowKeys[code]
    if not state.pressedKeys[code] then
      local transposedPitch = transposer.getTransposedPitch(kData.baseNote, false)
      state.pressedKeys[code] = transposedPitch
      if state.arpEnabled and state.arpBottomEnabled then
        arpeggiator.arpAddNote(code, transposedPitch)
      else
        midi.sendMidiNote("noteOn", transposedPitch, transposer.getEffectiveRowVelocity(false))
      end
      hud.updateWebviewHud()
    end
    return true
  elseif upperRowKeys[code] then
    local kData = upperRowKeys[code]
    if not state.pressedKeys[code] then
      local transposedPitch = transposer.getTransposedPitch(kData.baseNote, true)
      state.pressedKeys[code] = transposedPitch
      if state.arpEnabled and state.arpTopEnabled then
        arpeggiator.arpAddNote(code, transposedPitch)
      else
        midi.sendMidiNote("noteOn", transposedPitch, transposer.getEffectiveRowVelocity(true))
      end
      hud.updateWebviewHud()
    end
    return true
  elseif numberRowControls[code] then
    local cData = numberRowControls[code]
    if not state.pressedKeys[code] then
      state.pressedKeys[code] = true
      executeControlAction(cData.action, code)
    end
    return true
  elseif homeRowControls[code] then
    local cData = homeRowControls[code]
    if not state.pressedKeys[code] then
      state.pressedKeys[code] = true
      local act = state.shiftHeld and cData.shiftAction or cData.action
      executeControlAction(act, code)
    end
    return true
  end
  return false
end

local function handleKeyUp(code)
  if code == 50 then -- Backtick
    state.pressedKeys[code] = nil
    hud.updateWebviewHud()
    return true
  end

  if lowerRowKeys[code] or upperRowKeys[code] then
    local playedPitch = state.pressedKeys[code]
    if playedPitch then
      local isTop = upperRowKeys[code] ~= nil
      local arpEnabledForRow = isTop and state.arpTopEnabled or state.arpBottomEnabled
      if state.arpEnabled and arpEnabledForRow then
        arpeggiator.arpRemoveNote(code)
      else
        if not state.sustainActive then
          midi.sendMidiNote("noteOff", playedPitch, 0)
        end
      end
      state.pressedKeys[code] = nil
    end
    hud.updateWebviewHud()
    return true
  elseif numberRowControls[code] then
    state.pressedKeys[code] = nil
    hud.updateWebviewHud()
    return true
  elseif homeRowControls[code] then
    local cData = homeRowControls[code]
    state.pressedKeys[code] = nil
    local act = state.shiftHeld and cData.shiftAction or cData.action
    if act == "sustain" or act == "latch" then
      local holdDuration = hs.timer.secondsSinceEpoch() - state.sustainKeyDownTime
      if holdDuration > 0.25 then
        state.sustainActive = false
        midi.sendMidiCC(64, 0)
      else
        if state.sustainWasActiveOnPress then
          state.sustainActive = false
          midi.sendMidiCC(64, 0)
        else
          state.sustainActive = true
          midi.sendMidiCC(64, 127)
        end
      end

      if not state.sustainActive and state.arpEnabled then
        local numPhysicalHeld = 0
        for _ in pairs(state.arpKeysCurrentlyHeld) do numPhysicalHeld = numPhysicalHeld + 1 end
        if numPhysicalHeld == 0 then
          arpeggiator.stopArpTimer()
          state.arpHeldNotes = {}
        end
      end

      local spot = {
        title = "SUSTAIN / LATCH (CC #64)",
        value = state.sustainActive and "SUSTAIN ON" or "SUSTAIN OFF",
        subtext = state.sustainActive and "Notes & Arp pattern hold" or "Damping enabled",
        targetId = "key-0",
        color = state.sustainActive and "#d4a359" or "#b5aba0"
      }
      hud.updateWebviewHud(spot)
    else
      hud.updateWebviewHud()
    end
    return true
  end
  return false
end

return {
  executeControlAction = executeControlAction,
  handleKeyDown = handleKeyDown,
  handleKeyUp = handleKeyUp
}

end

__modules["midi"] = function()
local hsMidi = require("hs.midi")

_G.activeWatchers = _G.activeWatchers or {}

local function getMidiDevice()
  if _G.activeWatchers.midiDevice then return _G.activeWatchers.midiDevice end

  local devices = hsMidi.devices() or {}
  local virtualSources = hsMidi.virtualSources() or {}

  for _, devName in ipairs(devices) do
    if string.find(devName, "IAC") or string.find(devName, "Bus") then
      _G.activeWatchers.midiDevice = hsMidi.new(devName)
      return _G.activeWatchers.midiDevice
    end
  end

  for _, devName in ipairs(virtualSources) do
    if string.find(devName, "IAC") or string.find(devName, "Bus") then
      _G.activeWatchers.midiDevice = hsMidi.newVirtualSource(devName)
      return _G.activeWatchers.midiDevice
    end
  end

  if #devices > 0 then
    _G.activeWatchers.midiDevice = hsMidi.new(devices[1])
  elseif #virtualSources > 0 then
    _G.activeWatchers.midiDevice = hsMidi.newVirtualSource(virtualSources[1])
  end

  return _G.activeWatchers.midiDevice
end

local function sendMidiNote(cmd, noteNum, vel)
  local dev = getMidiDevice()
  if dev then
    dev:sendCommand(cmd, { note = noteNum, velocity = vel, channel = 0 })
  end
end

local function sendMidiCC(controllerNum, val)
  local dev = getMidiDevice()
  if dev then
    dev:sendCommand("controlChange", { controllerNumber = controllerNum, controllerValue = val, channel = 0 })
  end
end

return {
  getMidiDevice = getMidiDevice,
  sendMidiNote = sendMidiNote,
  sendMidiCC = sendMidiCC
}

end

return __require("init")
